version: "3.8"
services:
  postgres:
    container_name: db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: commands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d commands"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - net



networks:
  net:
    driver: bridge

volumes:
    db-data:
      name: cqrs
    db-admin-data:
      name: cqrs
    app-data:
      name: cqrs